# Generated by Django 5.1.1 on 2025-01-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('recipes', '0004_alter_favorite_user_alter_ingredientrecipe_amount_and_more'),
        ('users', '0002_alter_subscription_options_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
